# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='done',
            name='todo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='todo.Todo'),
        ),
        migrations.AlterField(
            model_name='expire',
            name='todo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='todo.Todo'),
        ),
    ]
