# Generated by Django 3.1.2 on 2020-10-08 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20170918_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='done',
            name='todo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='todo.todo'),
        ),
        migrations.AlterField(
            model_name='expire',
            name='todo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='todo.todo'),
        ),
    ]
